/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Code */
        post: operations["request_code_auth_request_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Code */
        post: operations["verify_code_auth_verify_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout_others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Others */
        post: operations["logout_others_auth_logout_others_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_me_patch"];
        trace?: never;
    };
    "/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Courses */
        get: operations["my_courses_me_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Sessions */
        get: operations["my_sessions_me_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_me_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dictionaries */
        get: operations["get_dictionaries_dictionaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Page */
        get: operations["course_page_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Program */
        get: operations["course_program_courses__course_id__program_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Reviews */
        get: operations["course_reviews_courses__course_id__reviews_get"];
        put?: never;
        /** Add Review */
        post: operations["add_review_courses__course_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/lead": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Lead */
        post: operations["create_lead_courses__course_id__lead_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson */
        get: operations["lesson_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Lesson */
        post: operations["complete_lesson_lessons__lesson_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson Playback */
        get: operations["lesson_playback_lessons__lesson_id__playback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/lesson/{file_id}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Lesson File */
        get: operations["download_lesson_file_files_lesson__file_id___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson File Link */
        get: operations["lesson_file_link_files__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Leads */
        get: operations["admin_leads_admin_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Lead */
        patch: operations["patch_lead_admin_leads__lead_id__patch"];
        trace?: never;
    };
    "/admin/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant Enrollment */
        post: operations["grant_enrollment_admin_enrollments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessGrantedOut */
        AccessGrantedOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "granted";
            /** Done Count */
            done_count: number;
            /** Total Count */
            total_count: number;
            /** Progress Percent */
            progress_percent: number;
            next_lesson: components["schemas"]["NextLessonOut"] | null;
        };
        /** AccessNoneOut */
        AccessNoneOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "none";
        };
        /** AccessRequestedOut */
        AccessRequestedOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "requested";
            /** Waiting Days */
            waiting_days: number;
        };
        /** AdminLeadCourseOut */
        AdminLeadCourseOut: {
            /** Id */
            id: number;
            /** Lang */
            lang: string;
            /** Title */
            title: string;
            /** Price */
            price: number | null;
        };
        /** AdminLeadOut */
        AdminLeadOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Price Snapshot */
            price_snapshot: number | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Waiting Days */
            waiting_days: number;
            /** Reminded At */
            reminded_at: string | null;
            teacher: components["schemas"]["LeadTeacherOut"];
            course: components["schemas"]["AdminLeadCourseOut"];
        };
        /** AdminLeadsPageOut */
        AdminLeadsPageOut: {
            /** Items */
            items: components["schemas"]["AdminLeadOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** Body_upload_file_files_post */
        Body_upload_file_files_post: {
            /** File */
            file?: string | null;
        };
        /** CatalogGroupOut */
        CatalogGroupOut: {
            /** Group Id */
            group_id: number;
            /** Langs */
            langs: string[];
            /** Rating */
            rating: number | null;
            /** Reviews Count */
            reviews_count: number;
            /** Versions */
            versions: components["schemas"]["CourseCardOut"][];
        };
        /** CatalogOut */
        CatalogOut: {
            /** Items */
            items: components["schemas"]["CatalogGroupOut"][];
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /**
         * CourseCardOut
         * @description Карточка версии курса — и в каталоге, и шапка страницы курса.
         */
        CourseCardOut: {
            /** Id */
            id: number;
            /** Lang */
            lang: string;
            /** Title */
            title: string;
            /** Category Id */
            category_id: number;
            /** Cover */
            cover: string | null;
            /** Hours */
            hours: number;
            /** Duration Text */
            duration_text: string | null;
            /** Price */
            price: number | null;
            /** Status */
            status: string;
            /** Starts At */
            starts_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Lessons Count */
            lessons_count: number;
            /** Students Count */
            students_count: number;
        };
        /** CoursePageOut */
        CoursePageOut: {
            /** Id */
            id: number;
            /** Lang */
            lang: string;
            /** Title */
            title: string;
            /** Category Id */
            category_id: number;
            /** Cover */
            cover: string | null;
            /** Hours */
            hours: number;
            /** Duration Text */
            duration_text: string | null;
            /** Price */
            price: number | null;
            /** Status */
            status: string;
            /** Starts At */
            starts_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Lessons Count */
            lessons_count: number;
            /** Students Count */
            students_count: number;
            /** Short */
            short: string;
            /** Full */
            full: string;
            /** Versions */
            versions: components["schemas"]["VersionChipOut"][];
            /** Rating */
            rating: number | null;
            /** Reviews Count */
            reviews_count: number;
            /** Strict Order */
            strict_order: boolean;
            /** Program */
            program: components["schemas"]["ProgramModuleOut"][];
            /** Access */
            access: components["schemas"]["AccessNoneOut"] | components["schemas"]["AccessRequestedOut"] | components["schemas"]["AccessGrantedOut"];
        };
        /** DictionariesOut */
        DictionariesOut: {
            /** Regions */
            regions: string[];
            /** Subjects */
            subjects: string[];
            /** Categories */
            categories: components["schemas"]["CategoryOut"][];
        };
        /** EnrollmentIn */
        EnrollmentIn: {
            /** User Id */
            user_id: number;
            /** Course Id */
            course_id: number;
            /** Paid */
            paid: boolean;
            /** Note */
            note?: string | null;
        };
        /** EnrollmentOut */
        EnrollmentOut: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Course Id */
            course_id: number;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Paid */
            paid: boolean;
            /** Note */
            note: string | null;
        };
        /** FileLinkOut */
        FileLinkOut: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeadOut */
        LeadOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Waiting Days */
            waiting_days: number;
        };
        /** LeadPatchIn */
        LeadPatchIn: {
            /** Status */
            status?: ("new" | "contacted" | "paid" | "granted" | "declined") | null;
            /** Note */
            note?: string | null;
        };
        /** LeadTeacherOut */
        LeadTeacherOut: {
            /** Id */
            id: number;
            /** Last Name */
            last_name: string;
            /** First Name */
            first_name: string;
            /** Middle Name */
            middle_name: string;
            /** Phone */
            phone: string;
            /** School */
            school: string;
            /** Region */
            region: string;
            /** Subject */
            subject: string;
        };
        /** LessonCompleteOut */
        LessonCompleteOut: {
            /** Is Completed */
            is_completed: boolean;
            /** Done Count */
            done_count: number;
            /** Total Count */
            total_count: number;
            /** Progress Percent */
            progress_percent: number;
            next_lesson: components["schemas"]["NextLessonOut"] | null;
        };
        /** LessonFileOut */
        LessonFileOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Mime */
            mime: string;
        };
        /** LessonOut */
        LessonOut: {
            /** Id */
            id: number;
            /** Module Id */
            module_id: number;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "text";
            /** Body */
            body: {
                [key: string]: unknown;
            } | null;
            /** Duration Label */
            duration_label: string | null;
            /** Time Required Min */
            time_required_min: number;
            /** Is Completed */
            is_completed: boolean;
            /** Files */
            files: components["schemas"]["LessonFileOut"][];
        };
        /** LogoutOthersOut */
        LogoutOthersOut: {
            /** Revoked Count */
            revoked_count: number;
        };
        /** MyCourseOut */
        MyCourseOut: {
            /** Id */
            id: number;
            /** Lang */
            lang: string;
            /** Title */
            title: string;
            /** Category Id */
            category_id: number;
            /** Cover */
            cover: string | null;
            /** Hours */
            hours: number;
            /** Price */
            price: number | null;
            /** Status */
            status: string;
            /** Done Count */
            done_count: number;
            /** Total Count */
            total_count: number;
            /** Progress Percent */
            progress_percent: number;
            next_lesson: components["schemas"]["NextLessonOut"] | null;
            /** Completed At */
            completed_at: string | null;
        };
        /** MyCoursesOut */
        MyCoursesOut: {
            /** Items */
            items: components["schemas"]["MyCourseOut"][];
            /** Leads */
            leads: components["schemas"]["MyLeadOut"][];
        };
        /** MyLeadCourseOut */
        MyLeadCourseOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Cover */
            cover: string | null;
            /** Price */
            price: number | null;
        };
        /** MyLeadOut */
        MyLeadOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Waiting Days */
            waiting_days: number;
            course: components["schemas"]["MyLeadCourseOut"];
        };
        /** NextLessonOut */
        NextLessonOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "text" | "quiz" | "task";
        };
        /** PlaybackOut */
        PlaybackOut: {
            /** Provider */
            provider: string;
            /** Url */
            url: string;
            /** Expires At */
            expires_at: string | null;
        };
        /** ProgramLessonOut */
        ProgramLessonOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text" | "video";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Time Required Min */
            time_required_min: number;
            /** Duration Label */
            duration_label: string | null;
        };
        /** ProgramLessonStatusOut */
        ProgramLessonStatusOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text" | "video";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Time Required Min */
            time_required_min: number;
            /** Duration Label */
            duration_label: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "locked" | "done";
        };
        /** ProgramModuleOut */
        ProgramModuleOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Items */
            items: (components["schemas"]["ProgramLessonOut"] | components["schemas"]["ProgramQuizOut"] | components["schemas"]["ProgramTaskOut"])[];
        };
        /** ProgramOut */
        ProgramOut: {
            /** Program */
            program: components["schemas"]["ProgramStatusModuleOut"][];
        };
        /** ProgramQuizOut */
        ProgramQuizOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "quiz";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Time Required Min */
            time_required_min: number;
            /** Questions Count */
            questions_count: number;
            /** Time Limit Min */
            time_limit_min: number | null;
            /** Pass Score */
            pass_score: number;
            /** Is Final */
            is_final: boolean;
        };
        /** ProgramQuizStatusOut */
        ProgramQuizStatusOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "quiz";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Time Required Min */
            time_required_min: number;
            /** Questions Count */
            questions_count: number;
            /** Time Limit Min */
            time_limit_min: number | null;
            /** Pass Score */
            pass_score: number;
            /** Is Final */
            is_final: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "locked" | "done";
        };
        /** ProgramStatusModuleOut */
        ProgramStatusModuleOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Items */
            items: (components["schemas"]["ProgramLessonStatusOut"] | components["schemas"]["ProgramQuizStatusOut"] | components["schemas"]["ProgramTaskStatusOut"])[];
        };
        /** ProgramTaskOut */
        ProgramTaskOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "task";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Time Required Min */
            time_required_min: number;
            /** Submit Format */
            submit_format: string;
        };
        /** ProgramTaskStatusOut */
        ProgramTaskStatusOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "task";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Time Required Min */
            time_required_min: number;
            /** Submit Format */
            submit_format: string;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "locked" | "done";
        };
        /** RequestCodeIn */
        RequestCodeIn: {
            /** Phone */
            phone: string;
            /** Consent */
            consent: boolean;
        };
        /** RequestCodeOut */
        RequestCodeOut: {
            /** Retry After Sec */
            retry_after_sec: number;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Rating */
            rating: number;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Id */
            id: number;
            /** Author Name */
            author_name: string;
            /** School */
            school: string;
            /** City */
            city: string;
            /** Rating */
            rating: number;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reply */
            reply?: null;
        };
        /** ReviewsPageOut */
        ReviewsPageOut: {
            /** Items */
            items: components["schemas"]["ReviewOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Rating */
            rating: number | null;
            /** Breakdown */
            breakdown: {
                [key: string]: number;
            };
        };
        /** SessionListOut */
        SessionListOut: {
            /** Items */
            items: components["schemas"]["SessionOut"][];
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** User Agent */
            user_agent: string;
            /** Is Current */
            is_current: boolean;
        };
        /** UploadedFileOut */
        UploadedFileOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Mime */
            mime: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Phone */
            phone: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Middle Name */
            middle_name: string;
            /** Photo Url */
            photo_url: string | null;
            /** Email */
            email: string;
            /** School */
            school: string;
            /** Position */
            position: string;
            /** Region */
            region: string;
            /** City */
            city: string;
            /** Subject */
            subject: string;
            /** Experience */
            experience: number | null;
            /** Lang */
            lang: string;
            /** Is Admin */
            is_admin: boolean;
            /** Onboarding Done */
            onboarding_done: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserPatch
         * @description Все поля необязательные: PATCH меняет только присланное.
         */
        UserPatch: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Middle Name */
            middle_name?: string | null;
            /** Email */
            email?: string | null;
            /** School */
            school?: string | null;
            /** Position */
            position?: string | null;
            /** Region */
            region?: string | null;
            /** City */
            city?: string | null;
            /** Subject */
            subject?: string | null;
            /** Experience */
            experience?: number | null;
            /** Lang */
            lang?: ("ru" | "kz") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyCodeIn */
        VerifyCodeIn: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
        };
        /** VersionChipOut */
        VersionChipOut: {
            /** Id */
            id: number;
            /** Lang */
            lang: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    request_code_auth_request_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_code_auth_verify_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_others_auth_logout_others_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutOthersOut"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    patch_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_courses_me_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyCoursesOut"];
                };
            };
        };
    };
    my_sessions_me_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListOut"];
                };
            };
        };
    };
    revoke_session_me_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dictionaries_dictionaries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionariesOut"];
                };
            };
        };
    };
    catalog_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogOut"];
                };
            };
        };
    };
    course_page_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_program_courses__course_id__program_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_reviews_courses__course_id__reviews_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewsPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_review_courses__course_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_courses__course_id__lead_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lesson_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_lesson_lessons__lesson_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonCompleteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lesson_playback_lessons__lesson_id__playback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedFileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_lesson_file_files_lesson__file_id___filename__get: {
        parameters: {
            query?: {
                e?: number;
                s?: string;
            };
            header?: never;
            path: {
                file_id: number;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lesson_file_link_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_leads_admin_leads_get: {
        parameters: {
            query?: {
                status?: ("new" | "contacted" | "paid" | "granted" | "declined" | "open") | null;
                course_id?: number | null;
                q?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLeadsPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_lead_admin_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_enrollment_admin_enrollments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
